#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);
use HTML::Entities;
use Email::Valid;
use Digest::SHA qw(sha1_hex);
use utf8;
use DateTime;

use lib "$Bin/../pm";

use HAL;
use HAL::DB;
use HAL::Util;
use HAL::Email;

my $db = new HAL::DB;
my $now = DateTime->now;
my $duesDay; # The next day for paying dues
my $daysLeft;
for my $nextMonth (0..1) {
	$duesDay = $now->clone;
	$duesDay->add(months=>1) if $nextMonth;
	$duesDay->set(day=>1);
	$duesDay->set(day => ((9-$duesDay->day_of_week)%7+3)); # Thursday after the first Tuesday.
	$daysLeft = int(($duesDay->epoch - $now->epoch) / (24*60*60));
	last if $daysLeft >= 0;
}

my $duesSoon = ($now->day >= 1 && $now->month == $duesDay->month) ? 1 : 0;
#print "Dues-day is: ".$duesDay->dmy." ($daysLeft days away soon=$duesSoon)\n";

my $SIG = "\n-- \nMed venlig hilsen HAL-900, OSAAs elektronhjerne.\n";
my $FROM = 'HAL på vegne af OSAA <hal@osaa.dk>';

my $mr = $db->sql("select m.id, m.dooraccess, monthlyFee, t.DoorAccess, membertype_id, email, realname, userName 
from member m inner join membertype t on (m.membertype_id=t.id)
where lastNagMail is null or lastNagMail + interval '5 days' < now()
order by m.id")
    or die "Urgh";
while (my ($id, $hasAccess, $fee, $getsAccess, $membertype_id, $email, $realname, $userName) = $mr->fetchrow_array) {

    next unless $realname;
    my ($firstname) = split /\s+/, $realname;

    my ($pbal, $account_id) = $db->getAccountTypeBalance($id, 2);
    $pbal ||= 0;
    my $bal = -$pbal;

    if ($account_id) { 

	if ($bal < 0) { # Overdraft!
	    $db->sql("update member set lastNagMail=now() where id=?", $id);

	    if ($daysLeft > 15) {
		my $email = sendmail($FROM, 
				     #"$realname <dren.dk\@gmail.com>",
				     "$realname <$email>",
				     "Advarsel om overtræk på din OSAA konto, $firstname",
"Hej, $firstname, du får denne mail fordi saldoen på din konto hos OSAA er gået i minus.

Lige nu står der $bal kr på din konto, vi beder dig indbetale mindst $pbal kr så hurtigt
som muligt, se denne side på HAL for oplysninger om betaling: https://hal.osaa.dk/hal/account/

OSAAs økonomi er alene baseret på medlemskontingentet, så vi håber på din fortsatte
støtte, men skulle du ikke længere ønske at være betalende medlem, beder vi dig logge ind
i HAL og skifte din medlemstype til gratis-medlem: https://hal.osaa.dk/hal/account/type samt
udligne ovetrækket ved at indbetale $pbal kr.

$SIG
"
		    );    
	    } else {
		my $email = sendmail($FROM, 
				     #"$realname <dren.dk\@gmail.com>",
				     "$realname <$email>",
				     "Advarsel om overtræk på din OSAA konto, $firstname",
"Hej, $firstname, du får denne mail fordi saldoen på din konto hos OSAA er gået i minus.

Lige nu står der $bal kr på din konto, vi beder dig indbetale mindst $pbal kr så hurtigt
som muligt, se denne side på HAL for oplysninger om betaling: https://hal.osaa.dk/hal/account/

Der er nu $daysLeft dage til du mister fordelene som betalende medlem, det betyder blandt
andet at du mister muligheden for at låse døren til lokalet op.

OSAAs økonomi er alene baseret på medlemskontingentet, så vi håber på din fortsatte
støtte, men skulle du ikke længere ønske at være betalende medlem, beder vi dig logge ind
i HAL og skifte din medlemstype til gratis-medlem: https://hal.osaa.dk/hal/account/type samt
udligne ovetrækket ved at indbetale $pbal kr.

$SIG
"
		    );    
	    }
	
	} elsif ($bal < $fee and $duesSoon) { # Not enough funds, will go into overdraft.
	    $db->sql("update member set lastNagMail=now() where id=?", $id);

	    my $email = sendmail($FROM, 
				 #"$realname <dren.dk\@gmail.com>",
				 "$realname <$email>",
				 "Advarsel om lav saldo på din OSAA konto, $firstname",
"Hej, $firstname, du får denne mail fordi saldoen på din konto hos OSAA er lavere end
kontingentet på $fee kr som trækkes snart.

Lige nu står der $bal kr på din konto.

Se denne side på HAL for oplysninger om betaling: https://hal.osaa.dk/hal/account/

OSAAs økonomi er alene baseret på medlemskontingentet, så vi håber på din fortsatte
støtte, men skulle du ikke længere ønske at være betalende medlem, beder vi dig logge ind
i HAL og skifte din medlemstype til gratis-medlem: https://hal.osaa.dk/hal/account/type

$SIG
"
		);    	    
	}	

    } elsif ($fee > 0) { # Never-paying (aka. new) member.
	$db->sql("update member set lastNagMail=now() where id=?", $id);

	my $email = sendmail($FROM, 
			     #"$realname <dren.dk\@gmail.com>",
			     "$realname <$email>",
			     "Velkommen som betalende medlem af Open Space Aarhus, $firstname",
"Hej, $firstname, du får denne mail fordi du har registreret dig som betalende medlem af OSAA.
OSAAs økonomi er alene baseret på kontingenter, så vi sætter stor pris på din støtte.

Så snart din betaling er registreret vil du få alle fordelene, men vi vil først trække
kontingentet fra din konto i starten af næste måned, så hvis du betaler nu får du resten af
måneden gratis.

Se denne side på HAL for oplysninger om betaling: https://hal.osaa.dk/hal/account/

Hvis du har valgt betalende medlem ved en fejl, beder vi dig logge ind i HAL og skifte din
medlemstype til gratis-medlem: https://hal.osaa.dk/hal/account/type

$SIG
"
	);    
    }
}
$mr->finish;

$db->dbh->commit;


