#!/usr/bin/perl
use strict;
use warnings;
use FindBin qw($Bin);
use HTML::Entities;
use Email::Valid;
use Digest::SHA qw(sha1_hex);
use utf8;

use lib "$Bin/../pm";

use HAL;
use HAL::DB;
use HAL::Util;
use HAL::Email;

my $db = new HAL::DB;

my $nu = $db->sql("select id, email, realname, userName, doorAccess ".
		  "from member where lastNagMail + interval '7 days' < now()") or die "Urgh";
while (my ($id, $email, $realname, $userName, $doorAccess) = $nu->fetchrow_array) {

    # Check for RFID, but only if doorAccess

    # Check for new accounts with no payments.



    my ($firstname) = split /\s+/, $realname;

    my $ue = escape_url($email);
    my $key = sha1_hex($email.'345klj56kl');	    
    my $url = "https://hal.osaa.dk/hal/create?email=$ue&key=$key&ex=37";

    print "$id\t$email\t$url\n";

    my $email = sendmail('OSAA <register@hal.osaa.dk>', 
			 #"$realname <dren.dk\@gmail.com>",
			 "$realname <$email>",
			 'Fortsæt Open Space Aarhus registreringen',
"Hej, $firstname, du får denne mail fordi du mangler at fuldføre din registrering som medlem af OSAA.

I medlemssystemet kan kan du bla. se alle dine indbetalinger, ændre dine kontakt oplysninger og
vælge PIN kode til brug sammen med din elektroniske nøgle.

Klik her for at fortsætte registreringen som medlem af Open Space Aarhus:
$url

-- 
Med venlig hilsen HAL900, på vegne af OSAA.
"
	);
}
$nu->finish;


